[phases.setup]
aptPkgs = [
  "libgobject-2.0-0",
  "libglib2.0-0", 
  "libpango-1.0-0",
  "libpangoft2-1.0-0",
  "libpangocairo-1.0-0",
  "libcairo2",
  "libgdk-pixbuf2.0-0",
  "libfontconfig1",
  "shared-mime-info",
  "fonts-liberation",
  "fonts-dejavu-core"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "bash start.sh"