[phases.setup]
aptPkgs = [
    "libpango-1.0-0",
    "libpangoft2-1.0-0",
    "libpangocairo-1.0-0",
    "libgobject-2.0-0",
    "libglib2.0-0",
    "libfontconfig1",
    "libcairo2",
    "libgdk-pixbuf-2.0-0",
    "libgdk-pixbuf2.0-0",
    "shared-mime-info",
    "fonts-liberation",
    "fonts-dejavu-core"
]

[start]
cmd = "bash start.sh"